// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
import 'package:pokebike/app/data/models/moto/moto.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'profile.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'profile.g.dart';

@freezed
class Profile with _$Profile {
  const factory Profile({
    required int id,
    required String username,
    required int numMotoCatturate,
    required int numVittorie,
    required int numSconfitte,
    int? favouriteMotoId,
    Moto? favouriteMoto,
  }) = _Profile;

  factory Profile.fromJson(Map<String, Object?> json) =>
      _$ProfileFromJson(json);

  factory Profile.fake(int index) => Profile(
        id: index,
        username: "Username $index",
        numMotoCatturate: 0,
        numVittorie: 0,
        numSconfitte: 0,
        favouriteMotoId: 1,
      );
}
