// This file is "main.dart"
import 'dart:developer';

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
import 'package:moto_hunters/app/data/models/api_media/api_media.dart';
import 'package:moto_hunters/app/data/models/marca_moto/marca_moto.dart';
import 'package:moto_hunters/app/data/models/tipo_moto/tipo_moto.dart';
import 'package:moto_hunters/app/shared/utils/mimage_provider.dart';
import 'package:get/get.dart';
import 'package:json_annotation/json_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'moto.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'moto.g.dart';

@freezed
class Moto with _$Moto {
  const factory Moto({
    required int id,
    @JsonKey(name: 'profile_id') required int profileId,
    @JsonKey(name: 'marca_moto') required MarcaMoto marcaMoto,
    @JsonKey(name: 'tipo_moto') required TipoMoto tipoMoto,
    required String nome,
    @Default('') String descrizione,
    @Default('') String luogo,
    @JsonKey(name: 'data_cattura') required DateTime dataCattura,
    int? anno,
    @JsonKey(name: 'num_vittorie') required int numVittorie,
    @JsonKey(name: 'num_sconfitte') required int numSconfitte,
    @JsonKey(name: 'last_torneo_id') int? lastTorneoId,
    @JsonKey(name: 'is_favorita') required bool isFavorita,
    String? cv,
    String? cc,
    @JsonKey(name: 'is_garage') required bool isGarage,
    ApiMedia? avatar,
    @JsonKey(name: 'photos') @Default(<ApiMedia>[]) List<ApiMedia> photos,
    @JsonKey(name: 'created_at') required DateTime createdAt,
    @JsonKey(name: 'updated_at') required DateTime updatedAt,
  }) = _Moto;

  factory Moto.fromJson(Map<String, Object?> json) => _$MotoFromJson(json);

  factory Moto.fake(int index) => Moto(
        id: index,
        profileId: 0,
        marcaMoto: MarcaMoto.fake(index),
        tipoMoto: TipoMoto.fake(index),
        nome: "Moto $index",
        descrizione:
            "Erede di un retaggio nato nel 1957, l’irriverente e ricercato Sportster S di Harley-Davidson evolve i tratti universalmente amati dei suoi predecessori: velocità scattante, agilità sorprendente e divertimento assicurato.",
        luogo: "Milano",
        dataCattura: DateTime.now(),
        anno: 2021,
        numVittorie: 0,
        numSconfitte: 0,
        lastTorneoId: null,
        isFavorita: true,
        cv: '',
        cc: '',
        isGarage: false,
        avatar:
            ApiMedia(id: index, url: MImageProvider.getImageUrl(index: index)),
        photos: [
          ApiMedia(id: index, url: MImageProvider.getImageUrl(index: index))
        ],
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      );
}
