// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
import 'package:pokebike/app/data/models/marca_moto/marca_moto.dart';
import 'package:pokebike/app/data/models/tipo_moto/tipo_moto.dart';
import 'package:pokebike/app/shared/utils/mimage_provider.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'moto.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'moto.g.dart';

@freezed
class Moto with _$Moto {
  const factory Moto({
    required int id,
    required String nome,
    required String descrizione,
    required int anno,
    required String luogo,
    required DateTime dataCattura,
    required MarcaMoto marcaMoto,
    required TipoMoto tipoMoto,
    required bool isFavorita,
    required int numVittorie,
    required int numSconfitte,
    required String avatar,
  }) = _Moto;

  factory Moto.fromJson(Map<String, Object?> json) => _$MotoFromJson(json);

  factory Moto.fake(int index) => Moto(
        id: index,
        nome: "Moto $index",
        descrizione:
            "Erede di un retaggio nato nel 1957, l’irriverente e ricercato Sportster S di Harley-Davidson evolve i tratti universalmente amati dei suoi predecessori: velocità scattante, agilità sorprendente e divertimento assicurato.",
        anno: 2021,
        luogo: "Milano",
        dataCattura: DateTime.now(),
        marcaMoto: MarcaMoto.fake(index),
        tipoMoto: TipoMoto.fake(index),
        numVittorie: 0,
        numSconfitte: 0,
        avatar: MImageProvider.getImageUrl(index: index),
        isFavorita: true
      );
}
