// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
import 'package:pokebike/app/shared/utils/mimage_provider.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'partecipazione.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'partecipazione.g.dart';

@freezed
class Partecipazione with _$Partecipazione {
  const factory Partecipazione({
    required int id,
    required int profileId,
    required int motoId,
    required int torneoId,
    required String fullName,
    required String avatar,
    required int punti,
  }) = _Partecipazione;

  factory Partecipazione.fromJson(Map<String, Object?> json) =>
      _$PartecipazioneFromJson(json);

  factory Partecipazione.fake(int index) => Partecipazione(
        id: index,
        profileId: index,
        motoId: index,
        torneoId: index,
        fullName: "Partecipante $index",
        avatar: MImageProvider.getImageUrl(index: index),
        punti: index,
      );
}
