// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
import 'package:moto_hunters/app/data/models/api_media/api_media.dart';
import 'package:moto_hunters/app/shared/utils/mimage_provider.dart';
import 'package:get/get.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'partecipazione.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'partecipazione.g.dart';

@freezed
class Partecipazione with _$Partecipazione {
  const factory Partecipazione({
    required int id,
    required int profileId,
    required int motoId,
    required int torneoId,
    required String fullName,
    ApiMedia? avatar,
    ApiMedia? motoAvatar,
    @Default([]) List<ApiMedia> motoPhotos,
    required int punti,
  }) = _Partecipazione;

  factory Partecipazione.fromJson(Map<String, Object?> json) =>
      _$PartecipazioneFromJson(json);

  factory Partecipazione.fake(int index) => Partecipazione(
        id: index,
        profileId: index,
        motoId: index,
        torneoId: index,
        fullName: "Partecipante $index",
        avatar:
            ApiMedia(id: index, url: MImageProvider.getImageUrl(index: index)),
        motoAvatar:
            ApiMedia(id: index, url: MImageProvider.getImageUrl(index: index)),
        motoPhotos: List.generate(3,
            (i) => ApiMedia(id: i, url: MImageProvider.getImageUrl(index: i))),
        punti: index,
      );
}
