// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'marca_moto.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'marca_moto.g.dart';

@freezed
class MarcaMoto with _$MarcaMoto {
  const factory MarcaMoto({
    required int id,
    required String nome,
  }) = _MarcaMoto;

  factory MarcaMoto.fromJson(Map<String, Object?> json) =>
      _$MarcaMotoFromJson(json);

  factory MarcaMoto.fake(int index) => MarcaMoto(
        id: index,
        nome: "Marca Moto $index",
      );
}
