// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'tipo_moto.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'tipo_moto.g.dart';

@freezed
class TipoMoto with _$TipoMoto {
  const factory TipoMoto({
    required int id,
    required String nome,
  }) = _TipoMoto;

  factory TipoMoto.fromJson(Map<String, Object?> json) => _$TipoMotoFromJson(json);
}
