// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:pokebike/app/data/models/partecipazione/partecipazione.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'turno.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'turno.g.dart';

@freezed
class Turno with _$Turno {
  const factory Turno({
    required int id,
    required Partecipazione partecipazione1,
    required Partecipazione partecipazione2,
    required int punti1,
    required int punti2,
    required int torneoId,
    int? vincitoreId,
    Partecipazione? vincitore
  }) = _Turno;

  factory Turno.fromJson(Map<String, Object?> json) => _$TurnoFromJson(json);
}
