// This file is "main.dart"
// import 'dart:math';

import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'notifica.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'notifica.g.dart';

@freezed
class Notifica with _$Notifica {
  const factory Notifica({
    required int id,
    required String title,
    required String body,
    required bool hasSeen,
    required DateTime receivedAt,
    DateTime? seenAt,
    String? image,
  }) = _Notifica;

  factory Notifica.fromJson(Map<String, Object?> json) =>
      _$NotificaFromJson(json);

  factory Notifica.fake(int index) => Notifica(
      id: index,
      title: "Notifica $index",
      body: "Body $index",
      hasSeen: false, // Random().nextDouble() <= 0.5,
      receivedAt: DateTime.now(),
      seenAt: null // DateTime.now()
      );
}
