// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS_XreIzqsXFakn_JyTSzDC6xJtrzjDLU',
    appId: '1:776310891261:android:9ed2c50455e76eefba1494',
    messagingSenderId: '776310891261',
    projectId: 'pokebike-1fc5d',
    storageBucket: 'pokebike-1fc5d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQnCXA5yfgGmuyEq0HY8roZX5b9vb6bvc',
    appId: '1:776310891261:ios:764e50a6529366f0ba1494',
    messagingSenderId: '776310891261',
    projectId: 'pokebike-1fc5d',
    storageBucket: 'pokebike-1fc5d.firebasestorage.app',
    androidClientId:
        '776310891261-3rqig8972hj76co96ie4ouogvteqfphc.apps.googleusercontent.com',
    iosClientId:
        '776310891261-64dv07g5f1726nn87lk2rsaurev0ernk.apps.googleusercontent.com',
    iosBundleId: 'com.resmedia.pokebike',
  );
}
